rly_file = "TrenDeLaCosta_BuenosAires.rly"
ttb_files = []
ssn_files = []
graphic_files = []
img_files = [ "TrendelaCosta_AR.bmp",]
doc_files = [ "README.md",]
release_date = "2022-02-08"
version = "1.0.0"
country_code = "AR"
factual = true
description = ""
display_name = "Tren De La Costa, Buenos Aires"
name = "Tren De La Costa (AR)"
author = "Krizar"
contributors = []
