rly_file = "TrenDeLaCosta_BuenosAires.rly"
ttb_files = [ "Horarios_Lunes_a_viernes_2022.ttb",]
ssn_files = []
graphic_files = []
img_files = [ "TrendelaCosta_AR.bmp",]
doc_files = [ "README.pdf",]
release_date = "2022-02-09"
version = "1.0.0"
country_code = "AR"
factual = true
description = "Surburban rail network along the coast north of Buenos Aires"
display_name = "Tren De La Costa, Buenos Aires"
name = "Tren De La Costa (AR)"
author = "Krizar"
contributors = []
